const fs = require('fs');
const path = require('path');

const packageJsonPath = path.resolve(__dirname, '../package.json');
const versionFilePath = path.resolve(__dirname, '../src/app/version.ts');

try {
    const packageJson = require(packageJsonPath);
    const version = packageJson.version;

    const content = `// This file is auto-generated by scripts/sync-version.js
export const APP_VERSION = '${version}';
`;

    fs.writeFileSync(versionFilePath, content, { encoding: 'utf8' });
    console.log(`Updated version to ${version} in ${versionFilePath}`);
} catch (error) {
    console.error('Error updating version:', error);
    process.exit(1);
}
